# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

[project]
name = "kebab"
version = "0.0.15"
description = "Knowledge Base construction and Access Benchmark (KeBAB)."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
dependencies = [
    "click",
    "numpy",
    "requests",
    "tqdm",
    "tiktoken",
    "transformers",
    "sentence-transformers",
    "nltk", # TODO(atorunova): replace with editdistance?
    "scipy",
    "evaluate",
    "rouge-score",
    "bert_score",
    "xlsxwriter",
    "openpyxl",
]

[build-system]
requires = ["uv_build>=0.7.19,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter",
    "matplotlib",
    "pandas",
    "plotly",
    "pyright",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "ruff",
    "torch>=2.8.0",

    # GPU support for gpt-oss requires triton, which does not support Windows builds.
    # "triton@git+https://github.com/triton-lang/triton.git@d441626",
    # "triton-kernels@git+https://github.com/triton-lang/triton.git@d441626#subdirectory=python/triton_kernels",
]

[tool.uv.build-backend]
module-root = ""
source-exclude = ["tests/**", "scripts/**", "docs/**", "build/**"]

[tool.pytest.ini_options]
pythonpath = ["kebab"]

[tool.pyright]
typeCheckingMode = "standard"
pythonVersion = "3.12"
exclude = ["**/__pycache__", "**/node_modules", "**/.*", "build"]
