# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "kebab"
version = "0.0.1"
description = "Knowledge Base construction and Access Benchmark (KeBAB)."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
dependencies = [
    "click",
    "numpy==2.2.4",
    "requests",
    "tqdm",
    "tiktoken",
    "sentence-transformers",
    "nltk", # TODO(atorunova): replace with editdistance?
    "scipy",
]

[project.optional-dependencies]
dev = [
    "jupyter",
    "matplotlib",
    "pandas",
    "plotly",
    "pyright==1.1.398",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "ruff==0.11.0",
]

all = ["kebab[dev]"]

[tool.setuptools.packages.find]
exclude = ["tests", "texts.*", "scripts", "scripts.*", "docs", "build"]

[tool.pytest.ini_options]
pythonpath = [
    "kebab"
]

[tool.setuptools.package-data]
"*" = ["py.typed", "configs/**/*"]

[tool.pyright]
typeCheckingMode = "standard"
exclude = [
    "**/__pycache__",
    "**/node_modules",
    "**/.*", # this covers .venv*
    "**/venv*",
    "**/ENV",
    "**/env",
]
pythonVersion = "3.12"

[tool.ruff]
extend = "scripts/validation/ruff.toml"