# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

[project]
name = "kebab"
version = "0.0.6"
description = "Knowledge Base construction and Access Benchmark (KeBAB)."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
dependencies = [
    "click",
    "numpy<2.2",
    "requests",
    "tqdm",
    "tiktoken",
    "transformers==4.50.3",
    "sentence-transformers",
    "nltk", # TODO(atorunova): replace with editdistance?
    "scipy",
    "evaluate",
    "rouge-score",
    "bert_score",
    "xlsxwriter",
]

[build-system]
requires = ["uv_build>=0.7.19,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "accelerate==1.6.0",
    "jupyter",
    "matplotlib",
    "pandas",
    "plotly",
    "pyright",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "ruff",
]

[tool.uv.build-backend]
module-root = ""
source-exclude = ["tests/**", "scripts/**", "docs/**", "build/**"]

[tool.pytest.ini_options]
pythonpath = ["kebab"]

[tool.pyright]
typeCheckingMode = "standard"
pythonVersion = "3.12"
exclude = ["**/__pycache__", "**/node_modules", "**/.*", "build"]
